apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: abuse-api-dev
images:
- name: gdartifactory1.jfrog.io/docker-dcu-local/hasher
  newTag: dev
- name: gdartifactory1.jfrog.io/docker-dcu-local/hashserve
  newTag: dev

configMapGenerator:
- literals:
  - NO_IMAGE_WORKER_THREADS=5
  - ENV=dev
  - LOG_LEVEL=DEBUG
  - ELASTIC_APM_ENVIRONMENT=dev
  name: env-specific-values
