apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: abuse-api-prod
images:
- name: gdartifactory1.jfrog.io/docker-dcu-local/hasher
  newTag: 1387a68
- name: gdartifactory1.jfrog.io/docker-dcu-local/hashserve
  newTag: prod

replicas:
- count: 4
  name: hashserve

configMapGenerator:
- literals:
  - NO_IMAGE_WORKER_THREADS=10
  - ENV=prod
  - LOG_LEVEL=INFO
  - ELASTIC_APM_ENVIRONMENT=prod
  name: env-specific-values
