apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: abuse-api-prod
images:
- name: docker-dcu-local.artifactory.secureserver.net/hashserve
  newTag: prod

replicas:
- name: thorn-worker
  count: 4

configMapGenerator:
- literals:
  - NO_IMAGE_WORKER_THREADS=10
  - ENV=prod
  - LOG_LEVEL=INFO
  name: hasher-env-specific-values

configMapGenerator:
- literals:
  - ENV=prod
  - LOG_LEVEL=INFO
  name: hasher-env-specific-values
