apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "hashserve"
  namespace: "abuse-api-ote"
  labels:
    app: "hashserve"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "hashserve"
  template:
    metadata:
      labels:
        app: "hashserve"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      imagePullSecrets:
        -
          name: "dcu-artifactory-creds"
      containers:
        - name: "hashserve"
          imagePullPolicy: "Always"
          image: "docker-dcu-local.artifactory.secureserver.net/hashserve:REPLACE_WITH_GIT_COMMIT"
          env:
            - name: BUILD_DATE
              value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
            - name: NO_IMAGE_WORKER_THREADS
              value: '10'
            - name: ENV
              value: ote
            - name: AMQP_BROKER
              valueFrom:
                secretKeyRef:
                  name: amqp-shared-creds
                  key: broker_url
            - name: MULTIPLE_BROKERS
              valueFrom:
                secretKeyRef:
                  name: amqp-shared-creds
                  key: multiple_brokers_pdna
            - name: LOG_LEVEL
              value: DEBUG
            - name: MAX_RETRY_COUNT
              value: '1'
            - name: queue-type
              value: quorum
        - name: "hasher"
          imagePullPolicy: "Always"
          image: "docker-dcu-local.artifactory.secureserver.net/hasher:e158a0d"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
          env:
            - name: PORT
              value: "8080"
            - name: ENV
              value: "ote"
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: ML_URL
              value: "http://127.0.0.1:8501/v1/models/small:classify"
            - name: ENABLE_ML_MODEL
              value: "true"
        - name: "hasher-ml"
          image: "docker-dcu-local.artifactory.secureserver.net/csamdetection"