apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: abuse-api-ote
images:
- name: docker-dcu-local.artifactory.secureserver.net/hasher
  newTag: 270a0d3
- name: docker-dcu-local.artifactory.secureserver.net/hashserve
  newTag: ote

configMapGenerator:
- literals:
  - NO_IMAGE_WORKER_THREADS=10
  - ENV=ote
  - LOG_LEVEL=DEBUG
  - ELASTIC_APM_ENVIRONMENT=ote
  name: env-specific-values
