apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: abuse-api-ote
images:
- name: gdartifactory1.jfrog.io/docker-dcu-local/hasher
  newTag: 1387a68
- name: gdartifactory1.jfrog.io/docker-dcu-local/hashserve
  newTag: ote


configMapGenerator:
- literals:
  - NO_IMAGE_WORKER_THREADS=10
  - ENV=ote
  - LOG_LEVEL=DEBUG
  - ELASTIC_APM_ENVIRONMENT=ote
  name: env-specific-values
