name: Run CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    runs-on: [csetubuntu]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Get Secrets
        id: secrets
        run: |
          SECRET=$(aws secretsmanager get-secret-value --secret-id '/GitHub/GitHub-Actions-Runner-PAT' --query 'SecretString' --output text)
          PAT=$(echo ${SECRET} | jq -r .PAT)
          echo "::set-output name=pat-cloud::${PAT}"
          echo "::add-mask::$PAT"
      - name: Checkout DCU actions
        uses: actions/checkout@v2
        with:
          repository: gdcorp-infosec/dcu-actions
          token: ${{ steps.secrets.outputs.pat-cloud }}
          path: local-actions/dcu-actions
      - name: GO CI
        uses: ./local-actions/dcu-actions/go
        with:
          main-path: github.com/gdcorp-infosec/hashserve/cmd/hashserve